### ISSUE TITLE
Communicating PIC with ESP8266 via RX/TX (serial)

### ISSUE THREAD

**Issue by bglima** [QueueManager/AttendantModule#2]
We need to implement or to find some lib to send/receive serial commands. Then, we need to send AT commands via serial to ESP8266. So, here is the steps for this issue:

1 - Learn how to user UART RX/TX communication with PIC16F688
2 - Learn how to store strings using assembly language
3 - Send AT strings via UART to ESP8266

It's possible to simulate a virtual serial port in Proteus. This [vídeo](https://www.youtube.com/watch?v=MgOITu9sv0k) shows the most basic form of it. Studying step 1 for now.

**Comment by bglima** [comment]
Here is the sequences for transmitting and receiving assynchronously:
To set up an **Asynchronous Transmission**:
1. Initialize the SPBRGH:SPBRG registers for the appropriate baud rate. Set or clear the BRGH
   and BRG16 bits, as required, to achieve the desired baud rate.
2. Enable the asynchronous serial port by clearing bit SYNC and setting bit SPEN. 
3. If interrupts are desired, set enable bit TXIE.
4. If 9-bit transmission is desired, set transmit bit TX9. Can be used as address/data bit.
5. Enable the transmission by setting bit TXEN, which will also set bit TXIF.
6. If 9-bit transmission is selected, the ninth bit should be loaded in bit TX9D.
7. Load data to the TXREG register (starts transmission). If using interrupts, ensure that the GIE and PEIE bits in the INTCON register (INTCON<7:6>) are set.

To set up **Asynchronous Receive**:
1. Initialize the SPBRGH:SPBRG registers for the appropriate baud rate. Set or clear the BRGH
   and BRG16 bits, as required, to achieve the desired baud rate.
2. Enable the asynchronous serial port by clearing bit SYNC and setting bit SPEN.
3. If interrupts are desired, set enable bit RCIE. 
4. If 9-bit reception is desired, set bit RX9.
5. Enable the reception by setting bit CREN.
6. Flag bit RCIF will be set when reception is complete and an interrupt will be generated if
   enable bit RCIE was set.
7. Read the RCSTA register to get the 9th bit (if enabled) and determine if any error occurred
   during reception.
8. Read the 8-bit received data by reading the RCREG register.
9. If any error occurred, clear the error by clearing enable bit CREN.
10. If using interrupts, ensure that the GIE and PEIE bits in the INTCON register (INTCON<7:6>) are
    set.

[Here](http://www.instructables.com/id/Fun-With-PIC-Assembly-Episode-18/step5/Software/), we have an example of [assembly](http://www.instructables.com/files/orig/FH1/BXNH/IGNXU31M/FH1BXNHIGNXU31M.txt) implementation of necessary routines.

**Comment by bglima** [comment]
Python script to convert a string into a assmebly data block. Used at serialModule\commandModule.inc.

```
#Put your AT command here
string = "AT+CWMODE=1"    

for c in string:
    print("    MOVLW   '%s'"%(c))
    print("    MOVWF    INDF")
    print("    INCF     FSR, F")

print("    MOVLW   0x0D            ; Carriage return")
print("    MOVWF   INDF")
print("    INCF    FSR, F")
print("    MOVLW   0x0A            ; Line feed")
print("    MOVWF   INDF")
print("    INCF    FSR, F")
print("    MOVLW   0x00            ; Use as end of text marker")
print("    MOVWF   INDF")

#Generated code must be pasted after MOVLW ATComXX 
#where XX is the command index'
```

You can run the above code online at [Repl.it](https://repl.it/languages/python3)

**Comment by matheuswhite** [comment]
@bglima @danielsanfr É necessário alguma configuração dos registradores _RCSTA_ e _TXSTA_ para a comunicação serial funcionar?

**Comment by bglima** [comment]
@tenoriomatheus, sim é necessário. No nosso [main.asm](https://github.com/QueueManager/AttendantModule.X/blob/master/mplabProject/main.asm), ao final do setup (linha 97), configuramos da seguinte forma:

```
       ; Configuring USART
      MOVLW   d'12'           ;9600 baud
      MOVWF   SPBRG
      BCF     PIR1,  RCIF     ;clear RX interrupt
      BSF     RCSTA, SPEN     ;serial port enable
      BSF     RCSTA, CREN     ;continuous RX enable
      BCF     TXSTA, SYNC     ;asynchronous mode
      BSF     TXSTA, TXEN     ;enable transmitter
```

Isso varia depedendo do modelo do PIC. No nosso caso, achamos um passo-a-passo na seção USART do datasheet do 16F688, ensinando como configurar envio e recepção assíncronos.

**Comment by bglima** [comment]
Communication all done, as you can see in [this GIF](https://raw.githubusercontent.com/QueueManager/AttendantModule.X/master/media/jobDone.gif)
