### ISSUE TITLE
Communicating Arduino to ESP-12 8266

### ISSUE THREAD

**Issue by clovisgabrielm** [QueueManager/AttendantModule#3]
It is necessary to disable RX and TX from Arduino before sending the code to it. It works in 5V and 3.3V. 

It is also necessary to connect VCC, GPIO0, GPI02 and EN to the 5V/3.3V in Arduino and GND, GPIO15 from ESP to GND from Arduino.

The default serial velocity is 115200 (blue cabe). You can test with the default program.

**Comment by bglima** [comment]
**Restart ESP8266**
AT+RST

**Set Wifi mode:**
AT+CWMODE?      _Query for testing which is the current mode_
AT+CWMODE=1    _STA mode_
AT+CWMODE=2    _AP  mode_
AT+CWMODE=3    _BOTH modes_

**Join Access point:**
AT+CWJAP?           _Query for testing which is the current Access Point_
AT+CWJAP="SSID","Password"   _Connect to an AP_

**Quit Access point:**
AT+CWQAP        _Quit current Access Point_

**Get current IP Address**
AT+CIFSR

**See which network you're connected**
AT+CWLAP

**Comment by bglima** [comment]
**How to init Client:**
AT+RST _;Reset device_  
AT+CWMODE=1 _;Set STA mode_
AT+CWJAP="dlink","" _;Connect to network"
AT+CIPMUX=1 _;Set multiple connections_
AT+CIPSTART=0,"TCP","192.168.0.101",1000 _;id, mode, server IP, port_

**How to init Server:**
AT+RST _Reset device_  
AT+CWMODE=1 _;Set STA mode_
AT+CWJAP="dlink","" _;Connect to network"
AT+CIPMUX=1 _;Set multiple connections_
AT+CIPSERVER=1,1000 _;mode(0 to delete or 1 to create),port_

**Comment by bglima** [comment]
**How to send messages after connection is stabilished**
AT+CIPSTART=0,"TCP","192.168.0.101",1000
AT+CIPSEND=_id_,_length_
AT+CIPCLOSE

**Comment by bglima** [comment]
**Change baud rate**
AT+CIOBAUD=9200

**Change Static IP**
AT+CIPSTA_DEF=”192.168.1.88” 

For more info about the commands, please visit [this reference](http://www.pridopia.co.uk/pi-doc/ESP8266ATCommandsSet.pdf).

**Comment by bglima** [comment]
Communication all done, as you can see in [this GIF](https://raw.githubusercontent.com/QueueManager/AttendantModule.X/master/media/jobDone.gif)
